import type { Metadata } from "next";
import { Roboto } from "next/font/google"

import "./components/main/main.css"
import "./components/main/Card/card.css"
import "./components/login/login.css"
import "./globals.css";

export const metadata: Metadata = {
  title: "WiceBank",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
