import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Footer from './components/foote/Footer'
import { UserProvider } from '@/context/UserContext'

import './components/main/main.css'
import './components/main/Card/card.css'
import './components/login/form.css'
import './globals.css'
import './components/main/Principal/principal.css'
import './components/initial-area/initial.css'
import './components/foote/footer.css'
import "./components/userinfo/userinfo.css"

export const metadata: Metadata = {
  title: 'WiceBank',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>
        <UserProvider>
        {children}
        </UserProvider>
        <Footer />
      </body>
    </html>
  )
}
